[gen_server]
    host = "0.0.0.0"
    port = 7000
    max_jobs = 5
    min_delay = 1.0
    save_path = "./data"
    token = ""
    always_require_auth = false
    
    [[gen_server.auth]]
        password = "123456"
        free_only = true
    
    [[gen_server.auth]]
        password = "aerlhkvsdjfh"
        free_only = false


[client]
    mode = "remote"
    autosave = true
    save_path = "./data_client"
    end_point = "http://127.0.0.1:7000"
    end_point_pswd = "123456"
    token = ""
    default_quality = "best quality, amazing quality, very aesthetic, absurdres"
    default_neg = "lowres, {bad}, worst quality, jpeg artifacts, watermark, signature, artistic error, username, scan, text"